markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: Hala Lossrual
    description: Machine Learning
    title: Machine Learning
    url: http://lossrual.github.com 
#duoshuo: chrispher2012
#tongji: 3F27793c8b949a643c724f32bcf5058791
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: lossrual
    email: lossrual@yahoo.com 
#weibo: 2917650677  # weibo ID
    github: lossrual  # github ID
#linkedin: chrispher-guan/5a/a68/6b8
#gplus: 110552447039675960964
    logo: http://lossrual.github.com/res/img/logo.jpg

